spring.application.name=solicitudes
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-orange-rain-apg7erpe-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_P7A2LwpshReN
spring.datasource.driver-class-name=org.postgresql.Driver


springdoc.swagger-ui.path=/doc/solicitud
springdoc.swagger-ui.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect